# Generated by Django 4.2.2 on 2023-07-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_main_resend_date',
            field=models.DateTimeField(default=None),
        ),
    ]
